import data from "@/data/countries.json";
import type { Country } from "./types";

/** All countries and territories (ISO 3166-1), generated by `npm run countries`. */
export const COUNTRIES = data as Country[];

const byCode = new Map(COUNTRIES.map((c) => [c.code, c]));

export function getCountry(code: string): Country | undefined {
  return byCode.get(code.toUpperCase());
}

export function countryName(code: string) {
  return byCode.get(code.toUpperCase())?.name ?? code;
}

export function searchCountries(query: string, limit = 8): Country[] {
  const q = query.trim().toLowerCase();
  if (!q) return [];
  const starts: Country[] = [];
  const contains: Country[] = [];
  for (const c of COUNTRIES) {
    const name = c.name.toLowerCase();
    if (name.startsWith(q) || c.code.toLowerCase() === q) starts.push(c);
    else if (name.includes(q) || c.capital.toLowerCase().includes(q)) contains.push(c);
  }
  return [...starts, ...contains].slice(0, limit);
}
